import type { ISchoolDelivery } from "@/types";

export const OPS_MOCK: ISchoolDelivery[] = [
  // ── MERAH: butuh perhatian segera ─────────────────────────────────────────
  {
    schoolId: "S001",
    schoolName: "SDN Mampang 01 Jakarta",
    produk: "RAPOR_KARAKTER",
    deliveryStage: "PENGERJAAN",
    hariTersisa: 2,
    progressPct: 48,
    trafficLight: "MERAH",
    bottleneckFlag: true,
    bottleneckDesc: "Koordinator sekolah belum kumpulkan data siswa kelas 4–6",
    csatScore: undefined,
  },
  {
    schoolId: "S002",
    schoolName: "SDIT Al-Ikhlas Depok",
    produk: "SCREENING",
    deliveryStage: "LAPORAN",
    hariTersisa: 1,
    progressPct: 75,
    trafficLight: "MERAH",
    bottleneckFlag: true,
    bottleneckDesc: "Laporan belum di-review kepala sekolah sejak 5 hari lalu",
    csatScore: undefined,
  },
  {
    schoolId: "S003",
    schoolName: "SDN Cibadak 02 Bogor",
    produk: "RAPOR_KARAKTER",
    deliveryStage: "PAPARAN",
    hariTersisa: 1,
    progressPct: 88,
    trafficLight: "MERAH",
    bottleneckFlag: false,
    csatScore: undefined,
  },
  {
    schoolId: "S004",
    schoolName: "TK Ananda Bunda Tangerang",
    produk: "RAPOR_PAUD",
    deliveryStage: "PERSIAPAN",
    hariTersisa: 2,
    progressPct: 15,
    trafficLight: "MERAH",
    bottleneckFlag: true,
    bottleneckDesc: "Enumerator belum konfirmasi jadwal observasi",
    csatScore: undefined,
  },

  // ── KUNING: at risk ────────────────────────────────────────────────────────
  {
    schoolId: "S005",
    schoolName: "SMP Islam Al-Azhar 1 Jakarta",
    produk: "RAPOR_KARAKTER",
    deliveryStage: "PENGERJAAN",
    hariTersisa: 5,
    progressPct: 55,
    trafficLight: "KUNING",
    bottleneckFlag: false,
    csatScore: undefined,
  },
  {
    schoolId: "S006",
    schoolName: "SDN Bintaro 05",
    produk: "SCREENING",
    deliveryStage: "PENGERJAAN",
    hariTersisa: 6,
    progressPct: 62,
    trafficLight: "KUNING",
    bottleneckFlag: false,
    csatScore: undefined,
  },
  {
    schoolId: "S007",
    schoolName: "SD Muhammadiyah 4 Bandung",
    produk: "RAPOR_KARAKTER",
    deliveryStage: "LAPORAN",
    hariTersisa: 4,
    progressPct: 80,
    trafficLight: "KUNING",
    bottleneckFlag: false,
    csatScore: undefined,
  },
  {
    schoolId: "S008",
    schoolName: "PAUD Ceria Pelangi Bekasi",
    produk: "RAPOR_PAUD",
    deliveryStage: "PERSIAPAN",
    hariTersisa: 5,
    progressPct: 22,
    trafficLight: "KUNING",
    bottleneckFlag: true,
    bottleneckDesc: "Pembayaran DP belum masuk dari sekolah",
    csatScore: undefined,
  },
  {
    schoolId: "S009",
    schoolName: "SDN Rawamangun 12",
    produk: "RAPOR_KARAKTER",
    deliveryStage: "PENGERJAAN",
    hariTersisa: 7,
    progressPct: 44,
    trafficLight: "KUNING",
    bottleneckFlag: false,
    csatScore: undefined,
  },

  // ── HIJAU: on track ────────────────────────────────────────────────────────
  {
    schoolId: "S010",
    schoolName: "SDIT Nurul Fikri Depok",
    produk: "RAPOR_KARAKTER",
    deliveryStage: "PENGERJAAN",
    hariTersisa: 14,
    progressPct: 58,
    trafficLight: "HIJAU",
    bottleneckFlag: false,
    csatScore: undefined,
  },
  {
    schoolId: "S011",
    schoolName: "SD Labschool Kebayoran",
    produk: "SCREENING",
    deliveryStage: "LAPORAN",
    hariTersisa: 10,
    progressPct: 85,
    trafficLight: "HIJAU",
    bottleneckFlag: false,
    csatScore: undefined,
  },
  {
    schoolId: "S012",
    schoolName: "SDN Pejaten Barat 07",
    produk: "RAPOR_KARAKTER",
    deliveryStage: "PAPARAN",
    hariTersisa: 12,
    progressPct: 91,
    trafficLight: "HIJAU",
    bottleneckFlag: false,
    csatScore: undefined,
  },
  {
    schoolId: "S013",
    schoolName: "TK Islam Bunga Bangsa",
    produk: "RAPOR_PAUD",
    deliveryStage: "PENGERJAAN",
    hariTersisa: 18,
    progressPct: 40,
    trafficLight: "HIJAU",
    bottleneckFlag: false,
    csatScore: undefined,
  },
  {
    schoolId: "S014",
    schoolName: "SD Advent Purwakarta",
    produk: "RAPOR_KARAKTER",
    deliveryStage: "PERSIAPAN",
    hariTersisa: 20,
    progressPct: 18,
    trafficLight: "HIJAU",
    bottleneckFlag: false,
    csatScore: undefined,
  },
  {
    schoolId: "S015",
    schoolName: "SDIT Ummul Quro Bogor",
    produk: "SCREENING",
    deliveryStage: "BELUM_MULAI",
    hariTersisa: 30,
    progressPct: 0,
    trafficLight: "HIJAU",
    bottleneckFlag: false,
    csatScore: undefined,
  },
  {
    schoolId: "S016",
    schoolName: "SD Integral Hidayatullah Bekasi",
    produk: "RAPOR_KARAKTER",
    deliveryStage: "BELUM_MULAI",
    hariTersisa: 25,
    progressPct: 0,
    trafficLight: "HIJAU",
    bottleneckFlag: false,
    csatScore: undefined,
  },

  // ── SELESAI ────────────────────────────────────────────────────────────────
  {
    schoolId: "S017",
    schoolName: "SDIT Jabal Nur Ciputat",
    produk: "RAPOR_KARAKTER",
    deliveryStage: "SELESAI",
    hariTersisa: 0,
    progressPct: 100,
    trafficLight: "HIJAU",
    bottleneckFlag: false,
    csatScore: 4.7,
  },
  {
    schoolId: "S018",
    schoolName: "SD Islam Terpadu Bina Insani Bogor",
    produk: "SCREENING",
    deliveryStage: "SELESAI",
    hariTersisa: 0,
    progressPct: 100,
    trafficLight: "HIJAU",
    bottleneckFlag: false,
    csatScore: 4.5,
  },
  {
    schoolId: "S019",
    schoolName: "TK Khalifah Depok",
    produk: "RAPOR_PAUD",
    deliveryStage: "SELESAI",
    hariTersisa: 0,
    progressPct: 100,
    trafficLight: "HIJAU",
    bottleneckFlag: false,
    csatScore: 4.9,
  },
  {
    schoolId: "S020",
    schoolName: "SD Al-Fath Cirendeu",
    produk: "RAPOR_KARAKTER",
    deliveryStage: "SELESAI",
    hariTersisa: 0,
    progressPct: 100,
    trafficLight: "HIJAU",
    bottleneckFlag: false,
    csatScore: 4.3,
  },
];
